### ISSUE TITLE
Extreme lag when loading large video files

### ISSUE THREAD

**Issue by flawedworld** [Lmh170/Android-Gallery-App#21]
Tested with The.Martian.2015.EXTENDED.2160p.UHD.BluRay.x265-TERMiNAL

**Comment by flawedworld** [comment]
Note that the video does play fine, it just takes forever to load. User may think that the app has crashed/frozen.

**Comment by Lmh170** [comment]
@flawedworld While I haven't been able to reproduce this issue, I have encountered several other issues with ExoPlayer when playing large files that I haven't been able to resolve. For now, I think it's best to replace it with videoView as implemented in the GrapheneOS Camera app.
